// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bin-personal-book/internal/biz"
	"bin-personal-book/internal/conf"
	"bin-personal-book/internal/data"
	"bin-personal-book/internal/server"
	"bin-personal-book/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	mongoData, cleanup, err := data.NewMonodbClient(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userZip := data.NewUserData(mongoData, logger)
	client := data.NewRedisClient(bootstrap, logger)
	redisZip := data.NewRedisData(client, logger)
	redisUsecase := biz.NewRedisUseBiz(confData, redisZip, logger)
	userUsecase := biz.NewUserUseBiz(confData, userZip, logger, redisUsecase)
	userService := service.NewUserService(userUsecase)
	tagsZip := data.NewTagsData(mongoData, logger)
	tagsUsecase := biz.NewTagsUseBiz(confData, tagsZip, logger)
	tagsService := service.NewTagsService(tagsUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, userService, tagsService, logger)
	uploadZip := data.NewUploadData(confData, mongoData, logger)
	uploadUsecase := biz.NewUploadBiz(confData, uploadZip, logger)
	uploadService := service.NewUploadService(uploadUsecase)
	httpServer := server.NewHTTPServer(bootstrap, userService, tagsService, uploadService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
