syntax = "proto3";

package api.user.v1;

import "google/api/annotations.proto";

option go_package = "bin-personal-book/api/user/v1;v1";

service Greeter {
  // 登录
  rpc Login(LoginParams) returns (LoginResult) {
    option (google.api.http) = {
      post : "/login",
      body : "*"
    };
  }

  // 注册
  rpc Register(RegisterParams) returns (RegisterResult) {
    option (google.api.http) = {
      post : "/register",
      body : "*"
    };
  }

  // 注册
  rpc SendCode(SendCodeParams) returns (SendCodeResult) {
    option (google.api.http) = {
      post : "/sendCode",
      body : "*"
    };
  }
}

message LoginParams {
  string account = 1;
  string password = 2;
}

message RegisterParams {
  string account = 1;
  string password = 2;
  string email = 3;
  string code = 4;
}

message LoginResult { string token = 1; }

message RegisterResult {}

message SendCodeParams { string email = 1; }

message SendCodeResult { string code = 1; }
