// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: upload/v1/upload.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadParams) Reset() {
	*x = UploadParams{}
	mi := &file_upload_v1_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadParams) ProtoMessage() {}

func (x *UploadParams) ProtoReflect() protoreflect.Message {
	mi := &file_upload_v1_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadParams.ProtoReflect.Descriptor instead.
func (*UploadParams) Descriptor() ([]byte, []int) {
	return file_upload_v1_upload_proto_rawDescGZIP(), []int{0}
}

type UploadResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResult) Reset() {
	*x = UploadResult{}
	mi := &file_upload_v1_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResult) ProtoMessage() {}

func (x *UploadResult) ProtoReflect() protoreflect.Message {
	mi := &file_upload_v1_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResult.ProtoReflect.Descriptor instead.
func (*UploadResult) Descriptor() ([]byte, []int) {
	return file_upload_v1_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_upload_v1_upload_proto protoreflect.FileDescriptor

const file_upload_v1_upload_proto_rawDesc = "" +
	"\n" +
	"\x16upload/v1/upload.proto\x12\rapi.upload.v1\x1a\x1cgoogle/api/annotations.proto\"\x0e\n" +
	"\fUploadParams\" \n" +
	"\fUploadResult\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2a\n" +
	"\aGreeter\x12V\n" +
	"\x06Upload\x12\x1b.api.upload.v1.UploadParams\x1a\x1b.api.upload.v1.UploadResult\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/uploadB$Z\"bin-personal-book/api/upload/v1;v1b\x06proto3"

var (
	file_upload_v1_upload_proto_rawDescOnce sync.Once
	file_upload_v1_upload_proto_rawDescData []byte
)

func file_upload_v1_upload_proto_rawDescGZIP() []byte {
	file_upload_v1_upload_proto_rawDescOnce.Do(func() {
		file_upload_v1_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_upload_v1_upload_proto_rawDesc), len(file_upload_v1_upload_proto_rawDesc)))
	})
	return file_upload_v1_upload_proto_rawDescData
}

var file_upload_v1_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_upload_v1_upload_proto_goTypes = []any{
	(*UploadParams)(nil), // 0: api.upload.v1.UploadParams
	(*UploadResult)(nil), // 1: api.upload.v1.UploadResult
}
var file_upload_v1_upload_proto_depIdxs = []int32{
	0, // 0: api.upload.v1.Greeter.Upload:input_type -> api.upload.v1.UploadParams
	1, // 1: api.upload.v1.Greeter.Upload:output_type -> api.upload.v1.UploadResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_upload_v1_upload_proto_init() }
func file_upload_v1_upload_proto_init() {
	if File_upload_v1_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_upload_v1_upload_proto_rawDesc), len(file_upload_v1_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_upload_v1_upload_proto_goTypes,
		DependencyIndexes: file_upload_v1_upload_proto_depIdxs,
		MessageInfos:      file_upload_v1_upload_proto_msgTypes,
	}.Build()
	File_upload_v1_upload_proto = out.File
	file_upload_v1_upload_proto_goTypes = nil
	file_upload_v1_upload_proto_depIdxs = nil
}
