// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             v5.26.1
// source: upload/v1/upload.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationGreeterUpload = "/api.upload.v1.Greeter/Upload"

type GreeterHTTPServer interface {
	// Upload 登录
	Upload(context.Context, *UploadParams) (*UploadResult, error)
}

func RegisterGreeterHTTPServer(s *http.Server, srv GreeterHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/upload", _Greeter_Upload0_HTTP_Handler(srv))
}

func _Greeter_Upload0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadParams
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Upload(ctx, req.(*UploadParams))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadResult)
		return ctx.Result(200, reply)
	}
}

type GreeterHTTPClient interface {
	// Upload 登录
	Upload(ctx context.Context, req *UploadParams, opts ...http.CallOption) (rsp *UploadResult, err error)
}

type GreeterHTTPClientImpl struct {
	cc *http.Client
}

func NewGreeterHTTPClient(client *http.Client) GreeterHTTPClient {
	return &GreeterHTTPClientImpl{client}
}

// Upload 登录
func (c *GreeterHTTPClientImpl) Upload(ctx context.Context, in *UploadParams, opts ...http.CallOption) (*UploadResult, error) {
	var out UploadResult
	pattern := "/upload"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationGreeterUpload),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
