// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: tags/v1/tags.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGreeterGetBillTagsList = "/api.tags.v1.Greeter/GetBillTagsList"
const OperationGreeterUpdateBillTags = "/api.tags.v1.Greeter/UpdateBillTags"

type GreeterHTTPServer interface {
	GetBillTagsList(context.Context, *GetBillTagsListParams) (*GetBillTagsListResult, error)
	UpdateBillTags(context.Context, *GetBillTagsInfo) (*UpdateBillTagsResult, error)
}

func RegisterGreeterHTTPServer(s *http.Server, srv GreeterHTTPServer) {
	r := s.Route("/")
	r.GET("/getBillTagsList", _Greeter_GetBillTagsList0_HTTP_Handler(srv))
	r.POST("/updateBillTags", _Greeter_UpdateBillTags0_HTTP_Handler(srv))
}

func _Greeter_GetBillTagsList0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBillTagsListParams
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterGetBillTagsList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBillTagsList(ctx, req.(*GetBillTagsListParams))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBillTagsListResult)
		return ctx.Result(200, reply)
	}
}

func _Greeter_UpdateBillTags0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBillTagsInfo
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterUpdateBillTags)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateBillTags(ctx, req.(*GetBillTagsInfo))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateBillTagsResult)
		return ctx.Result(200, reply)
	}
}

type GreeterHTTPClient interface {
	GetBillTagsList(ctx context.Context, req *GetBillTagsListParams, opts ...http.CallOption) (rsp *GetBillTagsListResult, err error)
	UpdateBillTags(ctx context.Context, req *GetBillTagsInfo, opts ...http.CallOption) (rsp *UpdateBillTagsResult, err error)
}

type GreeterHTTPClientImpl struct {
	cc *http.Client
}

func NewGreeterHTTPClient(client *http.Client) GreeterHTTPClient {
	return &GreeterHTTPClientImpl{client}
}

func (c *GreeterHTTPClientImpl) GetBillTagsList(ctx context.Context, in *GetBillTagsListParams, opts ...http.CallOption) (*GetBillTagsListResult, error) {
	var out GetBillTagsListResult
	pattern := "/getBillTagsList"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGreeterGetBillTagsList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) UpdateBillTags(ctx context.Context, in *GetBillTagsInfo, opts ...http.CallOption) (*UpdateBillTagsResult, error) {
	var out UpdateBillTagsResult
	pattern := "/updateBillTags"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterUpdateBillTags))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
