// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: tags/v1/tags.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBillTagsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillTagsInfo) Reset() {
	*x = GetBillTagsInfo{}
	mi := &file_tags_v1_tags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillTagsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillTagsInfo) ProtoMessage() {}

func (x *GetBillTagsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tags_v1_tags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillTagsInfo.ProtoReflect.Descriptor instead.
func (*GetBillTagsInfo) Descriptor() ([]byte, []int) {
	return file_tags_v1_tags_proto_rawDescGZIP(), []int{0}
}

func (x *GetBillTagsInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBillTagsInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBillTagsInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type GetBillTagsListParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillTagsListParams) Reset() {
	*x = GetBillTagsListParams{}
	mi := &file_tags_v1_tags_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillTagsListParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillTagsListParams) ProtoMessage() {}

func (x *GetBillTagsListParams) ProtoReflect() protoreflect.Message {
	mi := &file_tags_v1_tags_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillTagsListParams.ProtoReflect.Descriptor instead.
func (*GetBillTagsListParams) Descriptor() ([]byte, []int) {
	return file_tags_v1_tags_proto_rawDescGZIP(), []int{1}
}

type GetBillTagsListResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GetBillTagsInfo     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillTagsListResult) Reset() {
	*x = GetBillTagsListResult{}
	mi := &file_tags_v1_tags_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillTagsListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillTagsListResult) ProtoMessage() {}

func (x *GetBillTagsListResult) ProtoReflect() protoreflect.Message {
	mi := &file_tags_v1_tags_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillTagsListResult.ProtoReflect.Descriptor instead.
func (*GetBillTagsListResult) Descriptor() ([]byte, []int) {
	return file_tags_v1_tags_proto_rawDescGZIP(), []int{2}
}

func (x *GetBillTagsListResult) GetList() []*GetBillTagsInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetBillTagsListResult) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type UpdateBillTagsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBillTagsResult) Reset() {
	*x = UpdateBillTagsResult{}
	mi := &file_tags_v1_tags_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBillTagsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBillTagsResult) ProtoMessage() {}

func (x *UpdateBillTagsResult) ProtoReflect() protoreflect.Message {
	mi := &file_tags_v1_tags_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBillTagsResult.ProtoReflect.Descriptor instead.
func (*UpdateBillTagsResult) Descriptor() ([]byte, []int) {
	return file_tags_v1_tags_proto_rawDescGZIP(), []int{3}
}

var File_tags_v1_tags_proto protoreflect.FileDescriptor

var file_tags_v1_tags_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x74, 0x61, 0x67, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x76,
	0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x49, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x42, 0x69, 0x6c, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x22, 0x61, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x54, 0x61,
	0x67, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x30, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c,
	0x54, 0x61, 0x67, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x42, 0x69, 0x6c, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xed,
	0x01, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x73, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x42, 0x69, 0x6c, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42,
	0x69, 0x6c, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10, 0x2f,
	0x67, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x6d, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x54, 0x61, 0x67,
	0x73, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x3a, 0x01, 0x2a, 0x22, 0x0f, 0x2f,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x54, 0x61, 0x67, 0x73, 0x42, 0x22,
	0x5a, 0x20, 0x62, 0x69, 0x6e, 0x2d, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x2d, 0x62,
	0x6f, 0x6f, 0x6b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x61, 0x67, 0x73, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_tags_v1_tags_proto_rawDescOnce sync.Once
	file_tags_v1_tags_proto_rawDescData []byte
)

func file_tags_v1_tags_proto_rawDescGZIP() []byte {
	file_tags_v1_tags_proto_rawDescOnce.Do(func() {
		file_tags_v1_tags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tags_v1_tags_proto_rawDesc), len(file_tags_v1_tags_proto_rawDesc)))
	})
	return file_tags_v1_tags_proto_rawDescData
}

var file_tags_v1_tags_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tags_v1_tags_proto_goTypes = []any{
	(*GetBillTagsInfo)(nil),       // 0: api.tags.v1.GetBillTagsInfo
	(*GetBillTagsListParams)(nil), // 1: api.tags.v1.GetBillTagsListParams
	(*GetBillTagsListResult)(nil), // 2: api.tags.v1.GetBillTagsListResult
	(*UpdateBillTagsResult)(nil),  // 3: api.tags.v1.UpdateBillTagsResult
}
var file_tags_v1_tags_proto_depIdxs = []int32{
	0, // 0: api.tags.v1.GetBillTagsListResult.list:type_name -> api.tags.v1.GetBillTagsInfo
	1, // 1: api.tags.v1.Greeter.GetBillTagsList:input_type -> api.tags.v1.GetBillTagsListParams
	0, // 2: api.tags.v1.Greeter.UpdateBillTags:input_type -> api.tags.v1.GetBillTagsInfo
	2, // 3: api.tags.v1.Greeter.GetBillTagsList:output_type -> api.tags.v1.GetBillTagsListResult
	3, // 4: api.tags.v1.Greeter.UpdateBillTags:output_type -> api.tags.v1.UpdateBillTagsResult
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tags_v1_tags_proto_init() }
func file_tags_v1_tags_proto_init() {
	if File_tags_v1_tags_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tags_v1_tags_proto_rawDesc), len(file_tags_v1_tags_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tags_v1_tags_proto_goTypes,
		DependencyIndexes: file_tags_v1_tags_proto_depIdxs,
		MessageInfos:      file_tags_v1_tags_proto_msgTypes,
	}.Build()
	File_tags_v1_tags_proto = out.File
	file_tags_v1_tags_proto_goTypes = nil
	file_tags_v1_tags_proto_depIdxs = nil
}
